name: Android CI/CD Workflow

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create google-services.json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "app/src/google-services.json"
          json: ${{ secrets.FIREBASE_JSON }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.1.1'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test Java Code
        run: ./gradlew test

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Run the Gradle packageRelease task
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: packageRelease
          cache-disabled: false
          cache-read-only: true
          cache-write-only: false
          gradle-home-cache-includes: caches
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.8-1/x64
          JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.8-1/x64
          GRADLE_BUILD_ACTION_SETUP_COMPLETED: true
          GRADLE_BUILD_ACTION_CACHE_RESTORED: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs

      - name: Create google-services.json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "app/src/google-services.json"
          json: ${{ secrets.FIREBASE_JSON }}

      - name: Assemble app APK (debug)
        run: ./gradlew assembleDebug

      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Download app APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug

      - id: auth
        name: Authentication in Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}

      - name: Use Google Cloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Run Robo Tests in Firebase Test Lab
        run: gcloud firebase test android run --type robo --app /home/runner/work/TaskMuse/TaskMuse/app/build/outputs/apk/debug/app-debug.apk --timeout 5m